stages:
  - test
  - build

image: node:latest # Already have yarn installed

cache:
  paths:
    - node_modules/

before_script:
  - yarn

lint:
  stage: test
  script:
    - yarn lint:dry

unit_tests:
  stage: test
  script:
    - echo "Ignore img.src assignation errors"
    - yarn test:ci

build:
  stage: build
  script:
    - yarn build:prod
